using System;
namespace MouseGuardGMTool.Models
{
    public class TheGuard
    {
        public string Name { get; set; }
        public int Nature { get; set; }
        public int Will { get; set; }
        public int Health { get; set; }
        public int Resources { get; set; }
        public int Circles { get; set; }
        public int BirthYear { get; set; }
        public int CurrentAge { get; set; }
        public string Home { get; set; }
        public string FurColor { get; set; }
        public string Rank { get; set; }
        public string Cloak { get; set; }
        public string ParentA { get; set; }
        public bool AliveParetnA { get; set; }
        public string ParentB { get; set; }
        public bool AliveParetnB { get; set; }
        public string Senior { get; set; }
        public string Mentor { get; set; }
        public string Enemy { get; set; }
        public string Friend { get; set; }
        public string Belief { get; set; }
        public string Goal { get; set; }
        public string Instinct { get; set; }
        public string Traits { get; set; }

        //Skills
        public int Admin { get; set; }
        public int Apiarist { get; set; }
        public int Archivist { get; set; }
        public int Armorer { get; set; }
        public int Baker { get; set; }
        public int Boatcrafter { get; set; }
        public int Brewer { get; set; }
        public int Carpenter { get; set; }
        public int Cartographer { get; set; }
        public int Cook { get; set; }
        public int Deceiver { get; set; }
        public int Fighter { get; set; }
        public int Glazier { get; set; }
        public int Haggler { get; set; }
        public int Harvester { get; set; }
        public int Healer { get; set; }
        public int Hunter { get; set; }
        public int Insectrist { get; set; }
        public int Instructor { get; set; }
        public int Laborer { get; set; }
        public int Loremouse { get; set; }
        public int Militarist { get; set; }
        public int Miller { get; set; }
        public int Orator { get; set; }
        public int Pathfinder { get; set; }
        public int Persuader { get; set; }
        public int Potter { get; set; }
        public int Scientist { get; set; }
        public int Scout { get; set; }
        public int Smith { get; set; }
        public int Stonemason { get; set; }
        public int Survivalist { get; set; }
        public int Weather { get; set; }
        public int Watcher { get; set; }
        public int Weaver { get; set; }

        //Traits
        public int Bigpaw { get; set; }
        public int Bitter { get; set; }
        public int Bold { get; set; }
        public int Brave { get; set; }
        public int Calm { get; set; }
        public int Clever { get; set; }
        public int Compassionate { get; set; }
        public int Cunning { get; set; }
        public int Curious { get; set; }
        public int Deep { get; set; }
        public int Ear { get; set; }
        public int Defender { get; set; }
        public int Determined { get; set; }
        public int Driven { get; set; }
        public int EarlyRiser { get; set; }
        public int Extrovert { get; set; }
        public int Fat { get; set; }
        public int Fearful { get; set; }
        public int Fearless { get; set; }
        public int Fiery { get; set; }
        public int Generous { get; set; }
        public int Graceful { get; set; }
        public int GuardsOath { get; set; }
        public int Innocent { get; set; }
        public int Jaded { get; set; }
        public int Leader { get; set; }
        public int Longtail { get; set; }
        public int Lost { get; set; }
        public int NaturalBearings { get; set; }
        public int Nimble { get; set; }
        public int Nocturnal { get; set; }
        public int Oldfur { get; set; }
        public int QuickWitted { get; set; }
        public int Quiet { get; set; }
        public int Scarred { get; set; }
        public int SharpEyed { get; set; }
        public int Sharptooth { get; set; }
        public int Short { get; set; }
        public int Skeptical { get; set; }
        public int Skinny { get; set; }
        public int Stoic { get; set; }
        public int Stubborn { get; set; }
        public int Suspicious { get; set; }
        public int Tail { get; set; }
        public int Thoughful { get; set; }
        public int Tough { get; set; }
        public int WeatherSense { get; set; }
        public int Wise { get; set; }
        public int WolfsSnout { get; set; }
        public int Young { get; set; }
    }
}
